name: Generate and Deploy JSDoc

on:
  pull_request:
    branches:
      - main

jobs:
  documentation:
    runs-on: ubuntu-latest
    if: github.actor != 'actions-user'

    permissions:
      contents: write

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm install

      - name: Generate JSDoc Documentation
        run: npm run generate-docs

      - name: Commit Documentation
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Actions"
          git add docs
          git commit -m "Generated documentation"
          git push

